### ISSUE TITLE
Add fedora GCC image

### ISSUE THREAD

**Issue by NeroBurner** [openblack/openblack-docker#1]
Could we add a fedora gcc docker image to have a very recent gcc compiler (maybe even a clang compiler-image)

**Comment by janisozaur** [comment]
Sure, I can add fedora rawhide later. I should also document the process a bit.

**Comment by janisozaur** [comment]
Implemented in https://github.com/openblack/openblack-docker/commit/4668ace8be837b6b0873ee9e05263d2e7e4832e7 and https://github.com/openblack/openblack/pull/83
